### PR TITLE
FIX #23

### LINKED ISSUE #23: Fix documentation
Technical doc is mis-formatted, we should have a generation script & pass on the code to fix it.

### PR DESCRIPTION
**Pull request by aoqfonseca**
Adding a docs struct. This is a skeleton. The initial struct. Now, We should start write docs.

### CODE REVIEW

**Comment by Bladrak** [comment]
Seems good :) Do you want to keep this PR for submitting docs structure?

**Comment by aoqfonseca** [comment]
No. 

We can merge this and after we'll can write docs incrementally.   

What do you think about?

**Comment by Bladrak** [comment]
Ok sure, although I don't see the docs skeleton in the PR, did you create it or did you plan on creating it later?

**Comment by aoqfonseca** [comment]
We can create later. For now, we have just a index.rst with some examples and setup files( makefile, conf, etc).  

to generate, just go to command line and type: make docs.

**Comment by Bladrak** [comment]
Ok, thanks 👍

**Pull request merged**
