### PR TITLE
Using headers from context to store on meta

### PR DESCRIPTION
**Pull request by guilhermef**
This PR changes the way we get response headers,
It now uses context.headers, and fixes a problem if request._headers is called after finish().

### CODE REVIEW

**Comment by Bladrak** [comment]
Thanks !

**Comment by guilhermef** [comment]
Can you release a new version ?

**Comment by Bladrak** [comment]
@guilhermef I asked @masom to do this on the presigning PR :)

**Comment by guilhermef** [comment]
Thanks @Bladrak

**Comment by masom** [comment]
@guilhermef Will do right now.

Something we might want to figure out is how to allow more than 1 person to release on pypi.

**Comment by Bladrak** [comment]
@masom seems there's a way to designate maintainers: https://docs.python.org/2/distutils/packageindex.html

**Pull request merged**
