### PR TITLE
Check allowed sources, fixes #94

### LINKED ISSUE #94: ALLOWED_SOURCES option ignored with TC_AWS_ENABLE_HTTP_LOADER enabled?
It seems to me that ALLOWED_SOURCES is ignored with the TC_AWS_ENABLE_HTTP_LOADER option enabled.
If I load thumbor with the http_loader it correctly whitelist the hosts specified in ALLOWED_SOURCES, while with the S3 loade with http support this isn't the case.
Is there a specific parameter to allow the http sources, or am I missing something?
Thanks!

### PR DESCRIPTION
**Pull request by Bladrak**

### CODE REVIEW

**Comment by Bladrak** [comment]
Merging anyway, as the tests are broken waiting for https://github.com/nanvel/tornado-botocore/pull/12

**Comment by kkopachev** [comment]
Looks like it does not work. `ImagingHandler` tries to call `validate` [on loader, if it exists there. ](https://github.com/thumbor/thumbor/blob/6.4.1/thumbor/handlers/__init__.py#L532-L535)`validate` called with 2 arguments, while one implemented in this PR has 3 parameters defined. Which results in 
```
thumbor_1  | 2018-02-12 21:29:39 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
thumbor_1  |     yielded = self.gen.send(value)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 38, in check_image
thumbor_1  |     if not self.validate(kw['image']):
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 535, in validate
thumbor_1  |     is_valid = self.context.modules.loader.validate(self.context, path)
thumbor_1  | TypeError: validate() takes exactly 3 arguments (2 given)
```

**Comment by Bladrak** [comment]
Thanks for the report @kkopachev ; I've re-opened the issue and will try to fix this.

**Comment by Bladrak** [comment]
@kkopachev I've pushed a fix on 6.0.6 on pypi, let me know if that's ok now

**Comment by Bladrak** [comment]
Yes, sorry about that, I found out a bug afterwards that I fixed in the latest version (6.2.1). I mixed up the versions a bit, shouldn't try to maintain more than one branch anyways, as there are no BC Breaks.

**Pull request merged**
