### PR TITLE
[WIP] add workaround with TC_AWS_PRIVATE_HOST setting

### PR DESCRIPTION
**Pull request by phoet**
in order to work around #47

### CODE REVIEW

**Comment by Bladrak** [comment]
@phoet what is the purpose of this PR?

**Comment by phoet** [comment]
@Bladrak sorry, looks like the description got lost... i hope that i can fix the issues we are having with S3 urls in amazon VPCs.

**Comment by Bladrak** [comment]
Seems good so far :) Would you mind updating the tests as well?

**Comment by phoet** [comment]
@Bladrak unfortunately it does not work as expected :) if i have a working solution i will add tests for it and add documentation.

**Comment by phoet** [comment]
this is kinda fixed in botocore https://github.com/boto/botocore/issues/846

**Pull request closed without merging**
