### PR TITLE
Return datetime as utc

### PR DESCRIPTION
**Pull request by Bladrak**
- [x] https://github.com/thumbor/thumbor/pull/600
- [x] Release of PR within Thumbor
- [x] Update tc_aws version (and versionning)

### CODE REVIEW

**Comment by Bladrak** [comment]
@masom if you could give me your feedback on this, should be pretty straightforward, but we also implement a new pip versioning (following thumbor's).

**Comment by masom** [comment]
:+1:

**Comment by Bladrak** [comment]
I think I'll push it on another branch, until thumbor 6 is stable :)

**Comment by Bladrak** [comment]
Closing as this has been merged within https://github.com/thumbor-community/aws/tree/thumbor_6 branch

**Pull request closed without merging**
