### PR TITLE
More config options

### PR DESCRIPTION
**Pull request by phoet**

### CODE REVIEW

**Comment by Bladrak** [comment]
@phoet would you mind adding some docs explaining the changes you did? I understand there's some cleanup here, however this seems to induce a lot of BC Breaks. We should at least document how to migrate from the previous version to this one, don't you think?

**Comment by phoet** [comment]
Sorry this was a fuckup on my side. Please ignore the changes, they are meant for a private fork. I accidentally clicked on merge and restored the changes afterwards.

**Comment by Bladrak** [comment]
Oh ok, didn't see the revert, my bad :)

**Comment by phoet** [comment]
No worries, was my Fault

Hugo Briand <notifications@github.com> schrieb am Mo., 10. Okt. 2016, 17:15:

**Pull request merged**
