### PR TITLE
Refactored storage to factorize some code

### PR DESCRIPTION
**Pull request by Bladrak**
See #11

### CODE REVIEW

**Comment by masom** [comment]
@Bladrak Tests do cover this right?

**Comment by Bladrak** [comment]
@masom tests cover this partially; one of the storage is covered, but not the other one. However I'm not sur the current behavior is the expected one, I was hoping to discuss that but maybe this could go in another PR.

**Comment by Bladrak** [comment]
The uncovered storage is the result storage at the moment.

**Comment by masom** [comment]
@Bladrak Would you mind expanding on "However I'm not sure the current behavior is the expected one" ?

**Comment by Bladrak** [comment]
That's actually what's described in issue #11 ; the ``RESULT_STORAGE_AWS_STORAGE_ROOT_PATH`` is at the moment only used in the ``storage.s3_storage`` class, and not used in the ``result_storage.s3_storage`` class, which is odd.

**Comment by masom** [comment]
Not sure on this one. @dhardy92 ?

**Comment by dhardy92** [comment]
I suppose it would be 2 settings :
RESULT_STORAGE_AWS_STORAGE_ROOT_PATH
STORAGE_AWS_STORAGE_ROOT_PATH
that could be different maybe (we could use the same bucket for both as bucket number is limited by AWS to 100 per user)

What do you think ?

For now, setting RESULT_STORAGE_AWS_STORAGE_ROOT_PATH breaks my storage.
(didn't try this patch yet)

**Comment by Bladrak** [comment]
Seems better to me @dhardy92 :)
However, maybe this should be part of another PR? As this one concerns refactoring only. Adding an option would add another purpose to this PR, which wouldn't then be as atomic.

**Comment by dhardy92** [comment]
:+1: for another PR

**Comment by masom** [comment]
@Bladrak good to merge?

**Comment by Bladrak** [comment]
Seems so :)

**Comment by Bladrak** [comment]
@masom I'm currently working on PR #17 to add some tests on the other storage; maybe we should wait on this one to ensure the refactoring didn't break anything?

**Comment by masom** [comment]
Sure.

**Comment by Bladrak** [comment]
@masom should be done now :) All tests are passing

**Pull request merged**
