### PR TITLE
fixing pylint warnings

### PR DESCRIPTION
**Pull request by guilhermef**
I've fixed a few pylint warnings, regarding indentation, whitespace around operators and replacing a few equality conditions.

### CODE REVIEW

**Comment by Bladrak** [comment]
Great, needs to be rebased though :)

**Comment by guilhermef** [comment]
@Bladrak, Done rebasing
Could you release a new version on Pypi ?

**Comment by Bladrak** [comment]
@masom do you mind issuing a new version?

**Comment by masom** [comment]
@Bladrak @guilhermef 1.2.0 pushed to pypi

**Comment by guilhermef** [comment]
Thanks @masom and @Bladrak

**Pull request merged**
