### PR TITLE
Reuse Bucket and Botocore objects to prevent cyclic references

### LINKED ISSUE #109: Circular references when creating Botocore objects
I discovered recently, that even though thumbor with built-in loaders does not seem to leak (at least heavily), there are still a lot of collectible objects hanging in memory when using tc_aws for storage/loader.

Although, collectible objects does not mean there is a leak, from my understanding there is no guarantee gc will be ever run (or at least run before memkiller chimes in).

Digging dipper, with method described in https://github.com/thumbor/thumbor/issues/753#issuecomment-341584293 I realized that even creating vanilla botocore client and then deleting it would leave some circularly-referenced objects hanging in memory. This behavior also described in https://github.com/boto/botocore/issues/805

botocore team seems to think there is no issue, since all these objects collectible.

Loking at tc_aws package, I realized that code creates new botocore client every time thumbor calls loader. Which then calls Bucket, which calls [tornado_botocore](https://github.com/thumbor-community/aws/blob/master/tc_aws/aws/bucket.py#L43)

As far as I can see, we could instantiate Bucket objects just once per operation (get/put/delete) and reuse.

My testing shown 1760 objects collected after each creation of Bucket and making request to get a file from S3. However, if we reuse same Bucket object over multiple requests, number of collected objects falls to 34.

### PR DESCRIPTION
**Pull request by kkopachev**
calling `Botocore` on each call to loader/storage seems expensive, given that `tornado_botocore` object then creates `client` object, which has a bunch of cyclically referenced objects inside. About 1-2k of objects total. Eventually they are getting garbage collected, but why bother running expensive gc, when reusing same objects can improve things.

This PR essentially implementing ideas I outlined in #109. Collected garbage went down from 1600-1700 objects to 34 on each call to loader.

@Bladrak thoughts?

closes #109

### CODE REVIEW

**Comment by Bladrak** [comment]
Hi, and thanks for contributing :)
I'm wondering whether this doesn't duplicate a bit the logic within the session handler. Having a global bucket may remove the need for a global session. What do you think?

**Comment by Bladrak** [comment]
@kkopachev given I've merged the MAX_RETRY pull request, this one presents conflicts. I'd rather only publish one version with both fixes if that's ok with you?

**Comment by kkopachev** [comment]
@Bladrak that's totally fine with me releasing in one shot. I'll rebase this PR.

**Comment by kkopachev** [comment]
@Bladrak rebased on top of latest master, but discovered that thumbor for each request creates new storage/result storage instance, which ruins the whole idea :disappointed: 
We could make the Bucket objects for get/put/delete to be stored in global registry, but not sure how good idea is that. What do you think?

**Comment by Bladrak** [comment]
I'm not familiar with the global registry, is this handled by tornado?
Given the storage/result storage instances are directly handled by thumbor, we may not be able to do much here... Besides maybe trying to provide a singleton for those?

**Comment by kkopachev** [comment]
sorry, being busy lately.
Yes, I meant something like Singleton, but we'll have multiple instances, one per bucket+operation. I hope I could make these fixes soon.

**Comment by kkopachev** [comment]
@Bladrak I think this is ready. CircleCI issue seems unrelated to code changes, but rather CI config itself. Tests are passing locally. 

In short, `Bucket` object is now singleton (for a given set of arguments) and contains botocore clients on it, so it does not reinitialize everything on every request.

**Comment by Bladrak** [comment]
LGTM, I'm trying to have the tests pass before merging. Do you have some metrics about the improvements of GC?

**Comment by Bladrak** [comment]
@kkopachev could you rebase against master to use latest CI workflow? This should hopefully stabilize your PR :)

**Comment by kkopachev** [comment]
all green now!

**Comment by kkopachev** [comment]
FYI, I have a counterpart PR opened on botocore repo https://github.com/boto/botocore/pull/1450 which supposed to fix circularly referenced objects creation on each request.

**Comment by Bladrak** [comment]
Great thanks! I'll try to publish a new version today

**Pull request merged**
