### PR TITLE
FIX #72

### LINKED ISSUE #72: RESULT_STORAGE_EXPIRATION_SECONDS
First of all, thank you guys for your great work!

The [documentation of thumbor](https://github.com/thumbor/thumbor/wiki/Configuration#result_storage_expiration_seconds) distinguish between expiration of storage and result storage:

 - `RESULT_STORAGE_EXPIRATION_SECONDS`
 - `STORAGE_EXPIRATION_SECONDS`

In comparison tc_aws does not distinguish between and considers `STORAGE_EXPIRATION_SECONDS` for the result storage too.

### PR DESCRIPTION
**Pull request by aoqfonseca**
Moving storage_expiration_seconds definition to child class
then we can change this value depends on implementation. Like thumbor
do.

### CODE REVIEW

**Comment by Bladrak** [comment]
@aoqfonseca could you make 1 pull request per subject ? (i.e. 1 for the doc and 1 for the fix?) It's easier to track that way :)

**Comment by aoqfonseca** [comment]
Sure. 
It was a problem of my way to work. I should use a branch feature for this but i made everything at my master. I'll try to revert this and made a proper PR.

**Comment by aoqfonseca** [comment]
Done!

**Comment by Bladrak** [comment]
Ok, seems good, thanks :)

**Pull request merged**
